# See :~ https://gitlab.com/pages/plain-html/blob/master/.gitlab-ci.yml
# image: alpine:latest
image: node:12

pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master
